site_name: Plurality Korean Study Draft
site_url: https://normalist-k.github.io/plurality-ko-codex/
docs_dir: docs/korean

theme:
  name: material
  features:
    - navigation.expand
  palette:
    primary: black

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      toc_depth: 2

nav:
- Korean translation:
  - 홈: index.md
  - BEFORE YOU READ:
    - "0-0 Endorsements": "0-0-endorsements.md"
    - "0-1 About the Authors": "0-1-About-the-authors.md"
    - "0-2 Finding Your Dao": "0-2-finding-your-dao.md"
    - "0-3 Credits": "0-3-credits.md"
  - PREFACE:
    - "1 Seeing Plural": "1-preface.md"
  - INFORMATION TECHNOLOGY AND DEMOCRACY:
    - "2-0 A Widening Gulf": "2-0-information-technology-and-democracy-a-widening-gulf.md"
    - "2-1 A View from Yushan": "2-1-a-view-from-yushan.md"
    - "2-2 The Life of a Digital Democracy": "2-2-the-life-of-a-digital-democracy.md"
  - PLURALITY:
    - "3-0 What is ⿻?": "3-0-what-is-⿻.md"
    - "3-1 Living in a ⿻ World": "3-1-living-in-a-⿻-world.md"
    - "3-2 Connected Society": "3-2-connected-society.md"
    - "3-3 The Lost Dao": "3-3-the-lost-dao.md"
  - FREEDOM:
    - "4-0 Rights, Operating Systems and ⿻ Freedom": "4-0-rights-os-and-⿻-freedom.md"
    - "4-1 Identity and Personhood": "4-1-identity-and-personhood.md"
    - "4-2 Association and ⿻ Publics": "4-2-association-and-⿻-publics.md"
    - "4-3 Commerce and Trust": "4-3-commerce-and-trust.md"
    - "4-4 Property and Contract": "4-4-property-and-contract.md"
    - "4-5 Access": "4-5-access.md"
  - DEMOCRACY:
    - "5-0 Collaborative Technology and Democracy": "5-0-collaborative-technology-and-democracy.md"
    - "5-1 Post-Symbolic Communication": "5-1-post-symbolic-communication.md"
    - "5-2 Immersive Shared Reality": "5-2-immersive-shared-reality.md"
    - "5-3 Creative Collaborations": "5-3-creative-collaborations.md"
    - "5-4 Augmented Deliberation": "5-4-augmented-deliberation.md"
    - "5-5 Adaptive Administration": "5-5-adaptive-administration.md"
    - "5-6 ⿻ Voting": "5-6-⿻-voting.md"
    - "5-7 Social Markets": "5-7-social-markets.md"
  - IMPACT:
    - "6-0 From ⿻ to Reality": "6-0-from-⿻-to-reality.md"
    - "6-1 Workplace": "6-1-workplace.md"
    - "6-2 Health": "6-2-health.md"
    - "6-3 Media": "6-3-media.md"
    - "6-4 Environment": "6-4-environment.md"
    - "6-5 Learning": "6-5-learning.md"
  - FORWARD:
    - "7-0 Policy": "7-0-policy.md"
    - "7-1 Conclusion": "7-1-conclusion.md"
  - APPENDIX:
    - "8 Blurb": "8-blurb.md"
    - "Plurality Book Ownership List": "Plurality Book Ownership List.md"
